### ISSUE TITLE
Time step between saved images is inconsistent

### ISSUE THREAD

**Issue by formersbach** [ssandrews/Smoldyn#131] opened 2023-03-24 10:51 UTC
**Describe the bug**
The time displayed on saved tif images is inconsistent, changes between identically setup runs and is sometimes in the wrong order.

**To Reproduce**
- Edit: Download smoldyn version 2.71
- Add "tiff_iter 100" to template.txt (I added it under the graphical output section)
- Run simulation as usual
- Compare the times displayed on the saved images
- Re-running results in different displayed times
- Usually the first image is just black
- Occasionally the order of the images is also not correct (e.g. 1.23 -> 2.27 -> 6.32 -> 4.21), although I have not been able to reliably reproduce this.
- Edit: Was able to reproduce on both Ubuntu 22.04.2 LTS and Windows 11 on a Lenovo Thinkpad

**Expected behavior**
Time ranges from 0.00 to 10.00 in 1.00 increments (step_size * # of steps between saving). As far as I gathered from the manual the time step set in the config file is the actual timestep used and does not change dynamically.

**Screenshots**
Notice how the time a) does not start at 0 but at seemingly arbitrary 0.62 and b) does not increase by a constant factor between time steps:
![Example time sequence](https://user-images.githubusercontent.com/49982367/227500070-d93a96dd-6bf8-46c9-88b0-4e9098830f89.png)

Re-Running without changes to template.txt results in different timesteps:
![Example time sequence 2](https://user-images.githubusercontent.com/49982367/227501150-3b99e3a6-9b36-4134-a223-84ced2f4ff57.png)

**Files to reproduce**
[template.txt](https://github.com/ssandrews/Smoldyn/files/11061216/template.txt)

**Comment by ssandrews** [comment] 2023-03-30 03:45
Thanks for catching this issue. I repeated this test on an M1 Mac and got similar results. My first run had times at 0.01, 0.83, 2.01, 3.01, ... . Subsequent runs always had times at 0.01, 1.01, 2.01, 3.01, ... . I agree that image saving must be asynchronous somehow, although I'm not sure how. Smoldyn is single-threaded and is very unsophisticated in its graphics handling. In any case, I appreciate knowing about this and will look into it.

**Comment by formersbach** [comment] 2023-03-30 08:40
Thanks, I appreciate it!
Could this also affect saving data via cmd or is that completely separate?

**Comment by ssandrews** [comment] 2023-03-30 16:03
Saving data via cmd is completely separate, so that's not a concern. I've also used that fairly thoroughly and have never seen problems there. That said though, it still has the same timestep considerations, where the user might request a specific time interval, but what actually happens is limited by when each time step ends. For that reason, the integer-time queue can yield more expected results than the floating-time queue, and is also not susceptible to round-off error.

**Comment by ssandrews** [comment] 2023-04-07 17:28
I just fixed this issue and uploaded the fix to github. The problem was indeed asynchronous simulation and graphics, caused by the OpenGL function glutSwapBuffers, which only swaps the image buffers at monitor vertical refresh times. Anyhow, it's now fixed so now tiff files save at the requested times. I haven't made a release yet with this fix but can do so if it would be helpful. Otherwise, I'll wait until there are more changes before bothering to create a release.

**Closed** 2023-04-20 21:19 UTC
